"use client";

import { useMemo, useState } from "react";

const route = { id: "MX-07", name: "Corredor Norte · demo route" };

const scenarios = {
  mismatch: { label: "Persistent corridor shift", coverage: 86, trips: 212, persistence: "6/7 days", mismatch: 0.82, lead: "9 days", status: "Review recommended", note: "Observed trips repeatedly diverge from the official path in the same corridor." },
  stable: { label: "Normal operational variability", coverage: 88, trips: 219, persistence: "2/7 days", mismatch: 0.24, lead: "—", status: "No review signal", note: "Observed variation stays within the operational envelope." },
  insufficient: { label: "Insufficient observations", coverage: 42, trips: 74, persistence: "unknown", mismatch: null, lead: "unknown", status: "Do not conclude", note: "The system cannot distinguish stability from missing coverage in this window." },
} as const;
type ScenarioKey = keyof typeof scenarios;

export default function Home() {
  const [scenario, setScenario] = useState<ScenarioKey>("mismatch");
  const [analyzed, setAnalyzed] = useState(false);
  const [decision, setDecision] = useState<"keep" | "validate" | null>(null);
  const data = scenarios[scenario];
  const observedPath = useMemo(() => scenario === "mismatch" ? "M 95 315 C 190 300 245 245 340 265 S 505 355 625 300 S 735 225 820 105" : "M 95 315 C185 280 230 235 330 250 S510 325 620 245 S760 180 820 105", [scenario]);

  function chooseScenario(next: ScenarioKey) { setScenario(next); setAnalyzed(false); setDecision(null); }
  function runAnalysis() { setAnalyzed(true); setDecision(null); }

  return (
    <main className="min-h-screen bg-[#f6f6f1] text-[#172018]">
      <header className="sticky top-0 z-20 border-b border-[#dfe4dc] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#1f5a3a] text-sm font-black text-white">SD</div><div><p className="m-0 text-xs font-bold uppercase tracking-[0.16em] text-[#1f5a3a]">SEMOVI · DEMO</p><p className="m-0 text-sm font-semibold">Operational Change Evidence</p></div></div><div className="hidden items-center gap-3 sm:flex"><span className="rounded-full bg-[#eaf4ec] px-3 py-1.5 text-xs font-bold text-[#1f5a3a]">SIMULATED DATA</span><span className="text-xs text-[#657065]">Technologist MVP · Week 07</span></div></div></header>
      <div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 sm:py-10">
        <section className="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="max-w-3xl"><p className="mb-2 text-sm font-bold text-[#1f5a3a]">ROUTE REVIEW · {route.id}</p><h1 className="m-0 text-3xl font-black tracking-tight sm:text-4xl">Does the official representation still explain reality?</h1><p className="mt-3 max-w-2xl text-base leading-7 text-[#59635b]">A decision-support experiment that compares observed trips with the current route representation. It flags evidence for human review; it does not change the official dataset.</p></div><div className="flex gap-2 rounded-2xl border border-[#dfe4dc] bg-white p-1.5 shadow-sm">{(["mismatch","stable","insufficient"] as ScenarioKey[]).map(key => <button key={key} onClick={() => chooseScenario(key)} className={`rounded-xl px-3 py-2 text-xs font-bold transition ${scenario === key ? "bg-[#1f5a3a] text-white" : "text-[#59635b] hover:bg-[#f2f5f0]"}`}>{key === "mismatch" ? "Mismatch" : key === "stable" ? "Stable" : "Low coverage"}</button>)}</div></section>

        <section className="grid gap-5 lg:grid-cols-[1.45fr_0.75fr]">
          <div className="overflow-hidden rounded-3xl border border-[#dfe4dc] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#edf0eb] px-5 py-4 sm:px-6"><div><p className="m-0 text-xs font-bold uppercase tracking-[0.12em] text-[#657065]">Geospatial comparison</p><h2 className="mt-1 text-lg font-black">{route.name}</h2></div><span className="rounded-full bg-[#f2f5f0] px-3 py-1 text-xs font-semibold text-[#59635b]">7-day demo window</span></div><div className="p-4 sm:p-6"><div className="relative overflow-hidden rounded-2xl border border-[#e4e9e3] bg-[#eef1ec]"><svg viewBox="0 0 900 430" className="h-[330px] w-full sm:h-[390px]" role="img" aria-label="Simulated route comparison map"><defs><pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#dce2da" strokeWidth="1"/></pattern></defs><rect width="900" height="430" fill="url(#grid)"/><path d="M95 315 C185 280 230 235 330 250 S510 325 620 245 S760 180 820 105" fill="none" stroke="#1f5a3a" strokeWidth="11" strokeLinecap="round"/><path d={observedPath} fill="none" stroke="#9a5a00" strokeWidth="8" strokeDasharray="14 12" strokeLinecap="round"/>{[{x:95,y:315},{x:330,y:250},{x:620,y:245},{x:820,y:105}].map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="10" fill="#fff" stroke="#1f5a3a" strokeWidth="5"/>)}{scenario === "mismatch" && Array.from({length:24}).map((_,i)=><circle key={i} cx={180+((i*53)%570)} cy={265+((i*29)%95)} r="4" fill="#9a5a00" opacity=".65"/>)}<g fontFamily="Arial"><rect x="38" y="32" width="250" height="74" rx="14" fill="#fff" opacity=".96"/><text x="58" y="61" fontSize="12" fontWeight="700" fill="#657065">OFFICIAL REPRESENTATION</text><text x="58" y="87" fontSize="15" fontWeight="700" fill="#1f5a3a">A → B → C → D</text><rect x="610" y="32" width="250" height="74" rx="14" fill="#fff" opacity=".96"/><text x="630" y="61" fontSize="12" fontWeight="700" fill="#657065">OBSERVED TRIPS</text><text x="630" y="87" fontSize="15" fontWeight="700" fill="#9a5a00">{data.trips} simulated traces</text></g></svg><div className="absolute bottom-3 left-3 flex flex-wrap gap-2 rounded-xl bg-white/95 p-2 text-xs shadow"><span className="flex items-center gap-2"><i className="h-2.5 w-7 rounded-full bg-[#1f5a3a]"/> Official path</span><span className="flex items-center gap-2"><i className="h-0.5 w-7 border-t-2 border-dashed border-[#9a5a00]"/> Observed cluster</span></div></div><div className="mt-4 flex flex-col gap-3 rounded-2xl bg-[#f8faf7] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="m-0 text-xs font-bold uppercase tracking-[0.1em] text-[#657065]">Experiment input</p><p className="m-0 mt-1 text-sm font-semibold">Phone/GPS telemetry · simulated · no personal data</p></div><button onClick={runAnalysis} className="rounded-xl bg-[#1f5a3a] px-5 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-[#16432b]">{analyzed ? "Re-run analysis" : "Run analysis"}</button></div></div></div>
          <aside className="space-y-5"><MetricCard label="Observation coverage" value={`${data.coverage}%`} detail={data.coverage >= 70 ? "Sufficient coverage for this demo" : "Insufficient to conclude stability"} tone={data.coverage >= 70 ? "green" : "amber"}/><MetricCard label="Representation mismatch" value={analyzed && data.mismatch !== null ? data.mismatch.toFixed(2) : "—"} detail={analyzed ? data.status : "Run analysis to calculate"} tone={analyzed && data.mismatch !== null && data.mismatch >= .7 ? "amber" : "neutral"}/><div className="rounded-3xl border border-[#dfe4dc] bg-white p-5 shadow-sm"><p className="m-0 text-xs font-bold uppercase tracking-[0.12em] text-[#657065]">Coverage confidence</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-[#e4e9e3]"><div className="h-full rounded-full bg-[#1f5a3a] transition-all" style={{width:`${data.coverage}%`}}/></div><div className="mt-2 flex justify-between text-xs text-[#657065]"><span>{data.trips} trips observed</span><span>{data.persistence}</span></div><div className="mt-4 rounded-2xl bg-[#f7f8f5] p-3 text-xs leading-5 text-[#59635b]">Rule: low coverage means <b>unknown</b>, not stable. The system refuses to manufacture confidence from missing observations.</div></div></aside>
        </section>

        {analyzed && <section className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><article className="rounded-3xl border border-[#dfe4dc] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="m-0 text-xs font-bold uppercase tracking-[0.12em] text-[#657065]">Evidence package</p><h2 className="mt-1 text-xl font-black">{data.label}</h2></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${data.mismatch !== null && data.mismatch >= .7 ? "bg-[#fff3df] text-[#9a5a00]" : data.mismatch === null ? "bg-[#f1f2ef] text-[#657065]" : "bg-[#eaf4ec] text-[#1f5a3a]"}`}>{data.status}</span></div><p className="mt-4 text-sm leading-6 text-[#59635b]">{data.note}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Mini label="Coverage" value={`${data.coverage}%`}/><Mini label="Persistence" value={data.persistence}/><Mini label="Lead time" value={data.lead}/></div><div className="mt-5 rounded-2xl border border-[#edf0eb] p-4"><p className="m-0 text-xs font-bold uppercase tracking-[0.1em] text-[#657065]">What the system knows</p><ul className="mt-3 space-y-2 text-sm leading-6 text-[#59635b]"><li>• {data.trips} simulated trips were available in the observation window.</li><li>• Official path is compared against the observed path cluster.</li><li>• The signal is evidence for review, not an official route change.</li></ul></div></article><article className="rounded-3xl bg-[#1f5a3a] p-5 text-white shadow-sm sm:p-6"><p className="m-0 text-xs font-bold uppercase tracking-[0.12em] text-[#dcefe0]">Human review</p><h2 className="mt-2 text-xl font-black">What should happen next?</h2><p className="mt-2 text-sm leading-6 text-[#dcefe0]">The analyst owns the decision. The system never publishes or sanctions automatically.</p><div className="mt-6 grid gap-3"><button onClick={()=>setDecision("keep")} className={`rounded-xl px-4 py-3 text-sm font-bold ${decision === "keep" ? "bg-white text-[#1f5a3a]" : "bg-[#16432b] text-white hover:bg-[#123922]"}`}>Keep current representation</button><button onClick={()=>setDecision("validate")} className={`rounded-xl px-4 py-3 text-sm font-bold ${decision === "validate" ? "bg-white text-[#1f5a3a]" : "bg-[#16432b] text-white hover:bg-[#123922]"}`}>Request field validation</button></div>{decision && <div className="mt-4 rounded-2xl bg-white/10 p-4 text-sm leading-6"><b>Decision recorded for demo:</b> {decision === "keep" ? "keep current representation" : "request field validation"}. This is not a public update.</div>}</article></section>}
        <section className="mt-7 rounded-3xl border border-[#dfe4dc] bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="m-0 text-xs font-bold uppercase tracking-[0.12em] text-[#657065]">Experiment rule</p><p className="m-0 mt-1 text-sm font-semibold">Do not build unless the workflow beats the current human process on time or cost without reducing decision quality.</p></div><div className="rounded-xl bg-[#f2f5f0] px-4 py-3 text-center text-xs font-bold text-[#59635b]">Kill condition active</div></div></section>
      </div>
    </main>
  );
}

function MetricCard({label,value,detail,tone}:{label:string;value:string;detail:string;tone:"green"|"amber"|"neutral"}) { const c = tone === "green" ? "text-[#1f5a3a]" : tone === "amber" ? "text-[#9a5a00]" : "text-[#59635b]"; return <div className="rounded-3xl border border-[#dfe4dc] bg-white p-5 shadow-sm"><p className="m-0 text-xs font-bold uppercase tracking-[0.12em] text-[#657065]">{label}</p><p className={`m-0 mt-2 text-4xl font-black ${c}`}>{value}</p><p className="m-0 mt-2 text-xs leading-5 text-[#657065]">{detail}</p></div>; }
function Mini({label,value}:{label:string;value:string}) { return <div className="rounded-2xl bg-[#f7f8f5] p-3"><p className="m-0 text-[11px] font-bold uppercase tracking-[0.08em] text-[#657065]">{label}</p><p className="m-0 mt-1 text-lg font-black text-[#172018]">{value}</p></div>; }
